name: RELEASE TEST
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Step 1
        shell: cmd
        id: s
        run: |
          echo %GITHUB_ENV%
          echo ${{github.env}}
          echo "MY_VAR=MY_VAR_DATA" >> ${{github.env}}
          for /F %%l in (%GITHUB_ENV%) do (echo %%l)
      - name: Step 2
        shell: cmd
        id: s2
        run: |
          echo %MY_VAR%
