name: RELEASE TEST
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Step 1
        run: |
          echo "MY_VAR=MY_VAR_DATA" >> "$GITHUB_ENV"
          echo "MY_VAR2=MY_VAR2_DATA" >> "$GITHUB_ENV"
      - name: Step 2
        run: |
          echo $MY_VAR
          echo $MY_VAR2
          printf '%s\n' "$MY_VAR"
